### ISSUE TITLE
Implement interface methods (in `Lightsheet`) for all core methods that should be exposed

### ISSUE THREAD

**Issue by Yousif-FJ** [lightsheet-team/lightsheet#114]
- [ ] whoever is working on this should take a look at the event protocol as well

**Comment by Fluglow** [comment]
It came to my mind that we should probably also allow initializing a Lightsheet object without UI. This would allow loading data "in the background" and interacting with it using the usual interface methods, as well as referring to it in another sheet with UI (#101). Loosely related to this issue since it's a use case for the interface/package in general that we haven't really discussed before.
